name: Service Build and Deploy

on:
  workflow_call:
    inputs:
      node_version:
        description: "Node.js version to use"
        type: string
        default: "20"
      run_tests:
        description: "Whether to run pnpm run test"
        type: boolean
        default: true
      run_lint:
        description: "Whether to run pnpm run lint"
        type: boolean
        default: false
    secrets:
      NPM_TOKEN:
        required: true
      GCP_GCR_BUILD_SERVICE_ACCOINT_KEY:
        required: true
      GOLEE_REPO_DISPATCH_TOKEN:
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GCLOUD_SERVICE_ACCOUNT_KEYFILE: ${{ secrets.GCP_GCR_BUILD_SERVICE_ACCOINT_KEY }}

    outputs:
      image_path: ${{ steps.package.outputs.image_path }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Setup: pnpm"
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: "Setup: Node"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Test
        if: ${{ inputs.run_tests }}
        run: pnpm run test

      - name: Lint
        if: ${{ inputs.run_lint }}
        run: pnpm run lint

      - name: Package
        id: package
        uses: GoleeTeam/golee-build-action-workflow@v2.4
        with:
          name: ${{ github.repository }}
          branch: ${{ github.ref }}
          commit_hash: ${{ github.sha }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Trigger deploy-manager
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: GoleeTeam/deploy-manager
          token: ${{ secrets.GOLEE_REPO_DISPATCH_TOKEN }}
          event-type: deploy
          client-payload: '{"github": ${{ toJson(github) }}, "image_path": "${{ needs.build.outputs.image_path }}"}'
